/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;
import Model.Route;
import java.awt.Color;
import javax.swing.JLabel;

import org.w3c.dom.events.MouseEvent;

import java.awt.Dimension;
/**
 *
 * @author capta
 */
public class TuyenCard extends javax.swing.JPanel {
    private Route tuyen;
    /**
     * Creates new form TuyenCard
     */
    public TuyenCard() {
        initComponents();
        
    }
    public void setTuyen(Route tuyen) {
        this.tuyen = tuyen;
        Title.setText("<html><body style='width:120px'>" + tuyen.getRouteName() + "</body></html>");
        Title.revalidate();
        Title.repaint();
        this.setPreferredSize(new Dimension(150, 65));
        setOpaque(true);
        Title.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 235, 235));
        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        setPreferredSize(new java.awt.Dimension(150, 150));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        Title.setBackground(new java.awt.Color(235, 235, 235));
        Title.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Title.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        firePropertyChange("routeSelected", null, tuyen);
    }//GEN-LAST:event_formMouseClicked


    // Method to set the background color or perform any background-related logic
    public void setBackGroundClicked() {
        // Example: Change background color when selected
        setBackground(new Color(200, 200, 255));
        Title.setBackground(new Color(200, 200, 255));
        repaint();
    }
    public void setBackGroundNormal() {
        // Example: Change background color when selected
        setBackground(new Color(235, 235, 235));
        Title.setBackground(new Color(235, 235, 235));
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
